### ISSUE TITLE
ls-googleService.js is not easy to read on github's interface because the display is not indented correctly on that interface.

### ISSUE THREAD

**Issue by satvidh** [paulsjv/leansheets#8]
For example, see the following section of https://github.com/paulsjv/leansheets/blob/master/src/js/modules/leansheets/services/ls-googleService.js

![image](https://cloud.githubusercontent.com/assets/8485120/7429051/5bbe6260-efc0-11e4-90c2-a42d033a934b.png)

The arrows indicate areas indented incorrectly.

The code is not indented correctly in the github display. I suspect that it has to be a tabs vs spaces in the file issue. 

Fix the format so it displays correctly on github.

**Comment by paulsjv** [comment]
I took a look at the code in github and it seems to have corrected itself!
